# Generated by Django 3.2.8 on 2022-02-15 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.TextField()),
                ('input', models.TextField()),
                ('output', models.TextField()),
                ('title', models.TextField()),
            ],
        ),
    ]
