# Generated by Django 3.2.8 on 2022-02-15 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Problem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='datatype',
            field=models.CharField(default='int', max_length=20),
        ),
    ]
