# Generated by Django 3.2.8 on 2022-02-17 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Problem', '0003_problem_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='color',
            field=models.CharField(default='green', max_length=20),
        ),
    ]
